#ifndef GooglePlayGamesUnityPlugin_GPGSParams_h
#define GooglePlayGamesUnityPlugin_GPGSParams_h

// DO NOT EDIT THIS FILE. It is automatically generated by the Google Play Games
// Unity plugin and will be overwritten.

/*
  This section exists for the benefit of shell scripts (in particular,
  the post-processing script) that need to get information from this
  file:

AppId=661259641145
BundleId=com.teamsalt.hexciter
ClientId=661259641145-f0mcgo5um2iklm2prjesefc1hvvfcgpa.apps.googleusercontent.com

*/

#define kAppID "661259641145"
#define kBundleID "com.teamsalt.hexciter"
#define kClientID "661259641145-f0mcgo5um2iklm2prjesefc1hvvfcgpa.apps.googleusercontent.com"

#endif


